Migrate token storage
Insurlytech/zetapush-android pull request #9
Opened 2021-07-19 13:05 UTC by StevenWatremez

2021-07-19 16:32 UTC, jgoas requested changes

2021-07-19 16:32 UTC, jgoas commented on android-library/src/main/java/com/zetapush/library/ZetaPushService.kt
> +    @Deprecated(message = "Remove this method after 01/01/2022")
On va oublier lol

2021-07-19 16:32 UTC, jgoas commented on android-library/src/main/java/com/zetapush/library/storages/EncryptedSharedPreferenceFactory.kt
> +            "fileName",
tu n'utilises pas la valeur du fileName ?

2021-07-19 16:54 UTC, StevenWatremez commented on android-library/src/main/java/com/zetapush/library/ZetaPushService.kt
> +    @Deprecated(message = "Remove this method after 01/01/2022")
après si on oublie c'est pas grave :D on aura la nouvelle lib maybe/

2021-07-19 16:54 UTC, StevenWatremez commented on android-library/src/main/java/com/zetapush/library/storages/EncryptedSharedPreferenceFactory.kt
> +            "fileName",
je viens de modifier effectivement j'ai mis des "" sans faire exprès.

2021-07-20 06:11 UTC, anthonyGuiguen approved these changes

2021-07-20 07:43 UTC, jgoas requested changes

2021-07-20 07:43 UTC, jgoas commented on android-library/src/main/java/com/zetapush/library/storages/credentials/KeyValueCredentialsStorage.kt
> +        sharedPreferences.getString(keyLogin, null)?.let { login ->
Tu peux simplifier par : 
```
val login = sharedPreferences.getString(keyLogin, null)
val password = sharedPreferences.getString(keyPassword, null)
saveCredentials(login, password)
```

2021-07-20 07:43 UTC, jgoas commented on android-library/src/main/java/com/zetapush/library/storages/credentials/KeyValueCredentialsStorage.kt
> +        login?.let { login ->
J'aurais plutôt check si j'ai un login ou un password. Car généralement un mot de passe est lié au login, du coup si tu change l'un, tu est sur de changer l'autre. Voici ma proposition :  
```
if(!login.isNullOrBlank() || !password.isNullOrBlank()) {
  editor.putString(keyLogin, login)
  editor.putString(keyPassword, password)
}
```

2021-07-20 07:43 UTC, jgoas commented on android-library/src/main/java/com/zetapush/library/storages/token/KeyValueTokenStorage.kt
> +        token?.let { token ->
Question : Pourquoi avoir la possibilité d'avoir un token null et de ne rien faire avec ? Pourquoi ne pas faire directement : 
```
val editor = encryptedSharedPreferences.edit()
editor.putString(keyToken, token)
editor.apply()
```

2021-07-20 07:43 UTC, jgoas commented on android-library/src/main/java/com/zetapush/library/storages/token/KeyValueTokenStorage.kt
> +        encryptedSharedPreferences.all.forEach { edit.remove(it.key) }
encryptedSharedPreferences.clear() ?

2021-07-20 07:43 UTC, jgoas commented on android-library/src/main/java/com/zetapush/library/storages/token/KeyValueTokenStorage.kt
> +        sharedPreferences.getString(keyToken, null)?.let { token ->
Si modification plus haut alors tu peux directement faire : 
```
val token = sharedPreferences.getString(keyToken, null)
saveToken(token)
```

2021-07-20 08:10 UTC, jgoas approved these changes

2021-07-20 08:37 UTC, merged